name: edu_chatbot
description: AI Chatbot

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  responsive_builder: ^0.7.0
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  firebase_messaging: ^14.7.9
  firebase_analytics: ^10.7.4
  firebase_crashlytics: ^3.4.8
  firebase_ui_auth: ^1.12.0
  firebase_ui_oauth_google: ^1.2.16
  dio: ^5.4.0
  sqflite: ^2.3.0
  cached_network_image: ^3.3.1
  infinite_carousel: ^1.0.3
  intl: ^0.18.1
  path: ^1.8.3
  path_provider: ^2.1.1
  flutter_file_downloader: ^1.2.0
  get_it: ^7.6.4
  watch_it: ^1.2.0
  google_fonts: ^6.1.0
  mime: ^1.0.4
  shared_preferences: ^2.2.2
#  package_info_plus: ^5.0.1
  play_integrity_flutter: ^0.0.1
  archive: ^3.4.10
  universal_io: ^2.2.2
  pinput: ^3.0.1
  intl_phone_field: ^3.2.0
  flutter_sim_country_code: ^0.1.2
  dots_indicator: ^3.0.0
  flutter_dotenv: ^5.1.0
  url_launcher: ^6.2.2
  flutter_analog_clock: ^1.0.3
  sms_autofill: ^2.3.0
  video_thumbnail: ^0.5.3
  page_transition: ^2.1.0
  universal_platform: ^1.0.0+1
  device_info_plus: ^9.1.1
  fluttertoast: ^8.2.4
  pretty_json: ^2.0.0
  google_maps_flutter: ^2.5.1
  image: ^4.1.3
  json_annotation: ^4.8.1
  flutter_tex: ^4.0.6
  flutter_local_notifications: ^16.3.0
  badges: ^3.1.2
  focused_menu: ^1.0.5
  carousel_slider: ^4.2.1
  http: ^1.1.2
  webview_flutter: ^4.4.3
  flutter_rating_bar: ^4.0.1
  image_picker: ^1.0.6
  share_plus: ^7.2.1
  flutter_markdown: ^0.6.18+3
  flutter_image_compress: ^2.1.0
  http_parser: ^4.0.2
  pdf: ^3.10.7
  printing: ^5.11.1
  flutter_gemini: ^2.0.1
  lottie: ^2.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  build_runner: ^2.4.7
  mockito: ^5.4.4
  json_serializable: ^6.7.1


# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

